In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [3]:
df = pd.read_csv('applications.csv')

In [4]:
df

,Unnamed: 0,LOAN_ID,LOAN_DEFAULT,CONTRACT_TYPE,GENDER,OWN_CAR,OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,1,"100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,100003,0.0,Cash loans,F,N,N,0.0,270000.000,1293502.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,100004,0.0,Revolving loans,M,Y,Y,0.0,67500.000,135000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,100006,0.0,Cash loans,F,N,Y,0.0,135000.000,312682.5,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,5,100007,0.0,Cash loans,M,N,Y,0.0,121500.000,513000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,6,"100008,0,Cash loans,M,N,Y,0,99000.0,490495.5,2...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,100009,0.0,Cash loans,F,Y,Y,1.0,171000.000,1560726.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
7,8,100010,0.0,Cash loans,M,Y,Y,0.0,360000.000,1530000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,9,100011,0.0,Cash loans,F,N,Y,0.0,112500.000,1019610.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
9,10,100012,0.0,Revolving loans,M,N,Y,0.0,135000.000,405000.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
10,11,100014,0.0,Cash loans,F,N,Y,1.0,112500.000,652500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
11,12,100015,0.0,Cash loans,F,N,Y,0.0,38419.155,148365.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
12,13,100016,0.0,Cash loans,F,N,Y,0.0,67500.000,80865.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
13,14,100017,0.0,Cash loans,M,Y,N,1.0,225000.000,918468.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
14,15,100018,0.0,Cash loans,F,N,Y,0.0,189000.000,773680.5,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
15,16,100019,0.0,Cash loans,M,Y,Y,0.0,157500.000,299772.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16,17,100020,0.0,Cash loans,M,N,N,0.0,108000.000,509602.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
17,18,100021,0.0,Revolving loans,F,N,Y,1.0,81000.000,270000.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
18,19,"100022,0,Revolving loans,F,N,Y,0,112500.0,1575...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,100023,0.0,Cash loans,F,N,Y,1.0,90000.000,544491.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
20,21,"100024,0,Revolving loans,M,Y,Y,0,135000.0,4275...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,100025,0.0,Cash loans,F,Y,Y,1.0,202500.000,1132573.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0
22,23,100026,0.0,Cash loans,F,N,N,1.0,450000.000,497520.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
23,24,100027,0.0,Cash loans,F,N,Y,0.0,83250.000,239850.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
24,25,100029,0.0,Cash loans,M,Y,N,2.0,135000.000,247500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,26,"100030,0,Cash loans,F,N,Y,0,90000.0,225000.0,1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,100031,1.0,Cash loans,F,N,Y,0.0,112500.000,979992.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0
27,28,100032,0.0,Cash loans,M,N,Y,1.0,112500.000,327024.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,29,100033,0.0,Cash loans,M,Y,Y,0.0,270000.000,790830.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29,30,100034,0.0,Revolving loans,M,N,Y,0.0,90000.000,180000.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30721,30722,"135655,1,Cash loans,F,N,N,0,85500.0,814041.0,2...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30722,30723,135658,0.0,Cash loans,F,Y,Y,0.0,180000.000,508495.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
30723,30724,135659,0.0,Cash loans,F,N,Y,0.0,119250.000,679500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
30724,30725,135660,0.0,Revolving loans,F,N,Y,0.0,135000.000,157500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30725,30726,"135661,0,Cash loans,F,N,Y,0,94500.0,256500.0,1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30726,30727,"135662,0,Cash loans,F,N,Y,0,189000.0,722394.0,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30727,30728,135663,0.0,Cash loans,F,Y,Y,2.0,87493.500,450000.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30728,30729,135664,0.0,Cash loans,M,N,N,2.0,90000.000,862560.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
30729,30730,135665,0.0,Cash loans,F,N,N,0.0,54000.000,314100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
30730,30731,135666,1.0,Cash loans,F,N,Y,1.0,72000.000,95940.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
30731,30732,"135667,0,Cash loans,F,N,Y,0,157500.0,352044.0,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30732,30733,135668,0.0,Cash loans,F,N,Y,0.0,90000.000,269550.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
30733,30734,135669,1.0,Cash loans,F,N,Y,0.0,247500.000,1133748.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
30734,30735,135670,0.0,Cash loans,M,N,Y,0.0,180000.000,938304.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0
30735,30736,135671,0.0,Cash loans,F,Y,Y,0.0,81000.000,932643.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
30736,30737,135674,0.0,Cash loans,F,N,Y,0.0,112500.000,513531.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
30737,30738,"135675,0,Cash loans,F,N,N,0,45000.0,360000.0,1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30738,30739,"135676,1,Cash loans,F,Y,Y,1,202500.0,278712.0,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30739,30740,135677,0.0,Cash loans,F,N,N,0.0,112500.000,112068.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
30740,30741,135680,0.0,Cash loans,F,N,Y,0.0,112500.000,927000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
30741,30742,135681,0.0,Cash loans,F,N,Y,3.0,45000.000,348264.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0
30742,30743,135682,1.0,Cash loans,F,N,N,0.0,67500.000,298512.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
30743,30744,"135683,0,Cash loans,F,Y,Y,0,225000.0,2085120.0...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30744,30745,135685,0.0,Cash loans,F,Y,Y,2.0,202500.000,891072.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30745,30746,135686,1.0,Revolving loans,F,N,N,1.0,76500.000,180000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
30746,30747,"135687,0,Cash loans,F,N,N,0,198000.0,1546020.0...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30747,30748,135688,0.0,Cash loans,F,Y,N,0.0,112500.000,225000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
30748,30749,135689,0.0,Cash loans,M,N,N,0.0,90000.000,298512.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
30749,30750,135690,0.0,Cash loans,F,Y,Y,2.0,283500.000,2517300.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0
30750,30751,135691,0.0,Cash loans,M,Y,N,0.0,112500.000,1506816.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
df.describe()

,Unnamed: 0,LOAN_DEFAULT,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
count,30751.0000,23397.000000,23397.000000,2.339700e+04,2.339700e+04,23397.000000,2.337500e+04,23397.000000,23397.000000,23397.000000,...,23397.000000,23397.000000,23397.000000,23397.000000,20181.000000,20181.000000,20181.000000,20181.000000,20181.000000,20181.000000
mean,15376.0000,0.083173,0.420524,1.675337e+05,5.969064e+05,27082.672137,5.360546e+05,0.020647,-15995.186178,64023.880327,...,0.008249,0.000598,0.000556,0.000427,0.006888,0.007928,0.033299,0.268768,0.256727,1.891878
std,8877.1934,0.276150,0.727529,9.856913e+04,3.989251e+05,14569.858280,3.662844e+05,0.013882,4357.713390,141443.142415,...,0.090450,0.024455,0.023566,0.020670,0.087935,0.122885,0.201779,0.933736,0.603627,1.864967
min,1.0000,0.000000,0.000000,2.565000e+04,4.500000e+04,2052.000000,4.500000e+04,0.000533,-25166.000000,-16365.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7688.5000,0.000000,0.000000,1.125000e+05,2.700000e+05,16447.500000,2.385000e+05,0.010006,-19642.000000,-2750.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,15376.0000,0.000000,0.000000,1.440000e+05,5.123385e+05,24939.000000,4.500000e+05,0.018850,-15721.000000,-1221.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,23063.5000,0.000000,1.000000,2.025000e+05,8.086500e+05,34596.000000,6.795000e+05,0.028663,-12323.000000,-288.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
max,30751.0000,1.000000,9.000000,3.825000e+06,4.050000e+06,225000.000000,4.050000e+06,0.072508,-7689.000000,365243.000000,...,1.000000,1.000000,1.000000,1.000000,3.000000,6.000000,6.000000,24.000000,8.000000,25.000000

In [11]:
df_loan = df.dropna(subset=['LOAN_DEFAULT'])

In [12]:
df_loan.describe()

,Unnamed: 0,LOAN_DEFAULT,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
count,23397.000000,23397.000000,23397.000000,2.339700e+04,2.339700e+04,23397.000000,2.337500e+04,23397.000000,23397.000000,23397.000000,...,23397.000000,23397.000000,23397.000000,23397.000000,20181.000000,20181.000000,20181.000000,20181.000000,20181.000000,20181.000000
mean,15370.462111,0.083173,0.420524,1.675337e+05,5.969064e+05,27082.672137,5.360546e+05,0.020647,-15995.186178,64023.880327,...,0.008249,0.000598,0.000556,0.000427,0.006888,0.007928,0.033299,0.268768,0.256727,1.891878
std,8879.303536,0.276150,0.727529,9.856913e+04,3.989251e+05,14569.858280,3.662844e+05,0.013882,4357.713390,141443.142415,...,0.090450,0.024455,0.023566,0.020670,0.087935,0.122885,0.201779,0.933736,0.603627,1.864967
min,2.000000,0.000000,0.000000,2.565000e+04,4.500000e+04,2052.000000,4.500000e+04,0.000533,-25166.000000,-16365.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7667.000000,0.000000,0.000000,1.125000e+05,2.700000e+05,16447.500000,2.385000e+05,0.010006,-19642.000000,-2750.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,15320.000000,0.000000,0.000000,1.440000e+05,5.123385e+05,24939.000000,4.500000e+05,0.018850,-15721.000000,-1221.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,23086.000000,0.000000,1.000000,2.025000e+05,8.086500e+05,34596.000000,6.795000e+05,0.028663,-12323.000000,-288.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
max,30751.000000,1.000000,9.000000,3.825000e+06,4.050000e+06,225000.000000,4.050000e+06,0.072508,-7689.000000,365243.000000,...,1.000000,1.000000,1.000000,1.000000,3.000000,6.000000,6.000000,24.000000,8.000000,25.000000

In [13]:
df_loan

,Unnamed: 0,LOAN_ID,LOAN_DEFAULT,CONTRACT_TYPE,GENDER,OWN_CAR,OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
1,2,100003,0.0,Cash loans,F,N,N,0.0,270000.000,1293502.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,100004,0.0,Revolving loans,M,Y,Y,0.0,67500.000,135000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,100006,0.0,Cash loans,F,N,Y,0.0,135000.000,312682.5,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,5,100007,0.0,Cash loans,M,N,Y,0.0,121500.000,513000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,7,100009,0.0,Cash loans,F,Y,Y,1.0,171000.000,1560726.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
7,8,100010,0.0,Cash loans,M,Y,Y,0.0,360000.000,1530000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,9,100011,0.0,Cash loans,F,N,Y,0.0,112500.000,1019610.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
9,10,100012,0.0,Revolving loans,M,N,Y,0.0,135000.000,405000.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
10,11,100014,0.0,Cash loans,F,N,Y,1.0,112500.000,652500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
11,12,100015,0.0,Cash loans,F,N,Y,0.0,38419.155,148365.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
12,13,100016,0.0,Cash loans,F,N,Y,0.0,67500.000,80865.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
13,14,100017,0.0,Cash loans,M,Y,N,1.0,225000.000,918468.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
14,15,100018,0.0,Cash loans,F,N,Y,0.0,189000.000,773680.5,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
15,16,100019,0.0,Cash loans,M,Y,Y,0.0,157500.000,299772.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16,17,100020,0.0,Cash loans,M,N,N,0.0,108000.000,509602.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
17,18,100021,0.0,Revolving loans,F,N,Y,1.0,81000.000,270000.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
19,20,100023,0.0,Cash loans,F,N,Y,1.0,90000.000,544491.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
21,22,100025,0.0,Cash loans,F,Y,Y,1.0,202500.000,1132573.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0
22,23,100026,0.0,Cash loans,F,N,N,1.0,450000.000,497520.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
23,24,100027,0.0,Cash loans,F,N,Y,0.0,83250.000,239850.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
24,25,100029,0.0,Cash loans,M,Y,N,2.0,135000.000,247500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,27,100031,1.0,Cash loans,F,N,Y,0.0,112500.000,979992.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0
27,28,100032,0.0,Cash loans,M,N,Y,1.0,112500.000,327024.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,29,100033,0.0,Cash loans,M,Y,Y,0.0,270000.000,790830.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29,30,100034,0.0,Revolving loans,M,N,Y,0.0,90000.000,180000.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
30,31,100035,0.0,Cash loans,F,N,Y,0.0,292500.000,665892.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0
31,32,100036,0.0,Cash loans,F,N,Y,0.0,112500.000,512064.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,5.0
32,33,100037,0.0,Cash loans,F,N,N,0.0,90000.000,199008.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
33,34,100039,0.0,Cash loans,M,Y,N,1.0,360000.000,733315.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
36,37,100043,0.0,Cash loans,F,N,Y,2.0,198000.000,641173.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30711,30712,135644,0.0,Cash loans,F,N,Y,0.0,135000.000,971280.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0
30712,30713,135645,0.0,Revolving loans,F,Y,Y,0.0,315000.000,225000.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
30713,30714,135646,1.0,Cash loans,F,N,Y,0.0,108000.000,263686.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
30714,30715,135647,0.0,Cash loans,M,Y,N,0.0,157500.000,1546020.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
30715,30716,135648,1.0,Cash loans,M,N,Y,0.0,135000.000,364896.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30716,30717,135649,0.0,Revolving loans,F,N,Y,0.0,85500.000,135000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30717,30718,135651,0.0,Cash loans,M,N,N,1.0,180000.000,1288350.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30718,30719,135652,0.0,Revolving loans,M,Y,Y,2.0,261000.000,270000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
30722,30723,135658,0.0,Cash loans,F,Y,Y,0.0,180000.000,508495.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
30723,30724,135659,0.0,Cash loans,F,N,Y,0.0,119250.000,679500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
30724,30725,135660,0.0,Revolving loans,F,N,Y,0.0,135000.000,157500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30727,30728,135663,0.0,Cash loans,F,Y,Y,2.0,87493.500,450000.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30728,30729,135664,0.0,Cash loans,M,N,N,2.0,90000.000,862560.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
30729,30730,135665,0.0,Cash loans,F,N,N,0.0,54000.000,314100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
30730,30731,135666,1.0,Cash loans,F,N,Y,1.0,72000.000,95940.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
30732,30733,135668,0.0,Cash loans,F,N,Y,0.0,90000.000,269550.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
30733,30734,135669,1.0,Cash loans,F,N,Y,0.0,247500.000,1133748.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
30734,30735,135670,0.0,Cash loans,M,N,Y,0.0,180000.000,938304.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0
30735,30736,135671,0.0,Cash loans,F,Y,Y,0.0,81000.000,932643.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
30736,30737,135674,0.0,Cash loans,F,N,Y,0.0,112500.000,513531.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
30739,30740,135677,0.0,Cash loans,F,N,N,0.0,112500.000,112068.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
30740,30741,135680,0.0,Cash loans,F,N,Y,0.0,112500.000,927000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
30741,30742,135681,0.0,Cash loans,F,N,Y,3.0,45000.000,348264.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0
30742,30743,135682,1.0,Cash loans,F,N,N,0.0,67500.000,298512.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
30744,30745,135685,0.0,Cash loans,F,Y,Y,2.0,202500.000,891072.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30745,30746,135686,1.0,Revolving loans,F,N,N,1.0,76500.000,180000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
30747,30748,135688,0.0,Cash loans,F,Y,N,0.0,112500.000,225000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
30748,30749,135689,0.0,Cash loans,M,N,N,0.0,90000.000,298512.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
30749,30750,135690,0.0,Cash loans,F,Y,Y,2.0,283500.000,2517300.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0
30750,30751,135691,0.0,Cash loans,M,Y,N,0.0,112500.000,1506816.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
df_clean = df_loan.drop(['Unnamed: 0', 'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_QRT','AMT_REQ_CREDIT_BUREAU_YEAR'], axis=1)
df_clean

,LOAN_ID,LOAN_DEFAULT,CONTRACT_TYPE,GENDER,OWN_CAR,OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_MON
1,100003,0.0,Cash loans,F,N,N,0.0,270000.000,1293502.5,35698.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0.0,Revolving loans,M,Y,Y,0.0,67500.000,135000.0,6750.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0.0,Cash loans,F,N,Y,0.0,135000.000,312682.5,29686.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
4,100007,0.0,Cash loans,M,N,Y,0.0,121500.000,513000.0,21865.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,100009,0.0,Cash loans,F,Y,Y,1.0,171000.000,1560726.0,41301.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
7,100010,0.0,Cash loans,M,Y,Y,0.0,360000.000,1530000.0,42075.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,100011,0.0,Cash loans,F,N,Y,0.0,112500.000,1019610.0,33826.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,100012,0.0,Revolving loans,M,N,Y,0.0,135000.000,405000.0,20250.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
10,100014,0.0,Cash loans,F,N,Y,1.0,112500.000,652500.0,21177.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11,100015,0.0,Cash loans,F,N,Y,0.0,38419.155,148365.0,10678.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,100016,0.0,Cash loans,F,N,Y,0.0,67500.000,80865.0,5881.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
13,100017,0.0,Cash loans,M,Y,N,1.0,225000.000,918468.0,28966.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,100018,0.0,Cash loans,F,N,Y,0.0,189000.000,773680.5,32778.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
15,100019,0.0,Cash loans,M,Y,Y,0.0,157500.000,299772.0,20160.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,100020,0.0,Cash loans,M,N,N,0.0,108000.000,509602.5,26149.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,100021,0.0,Revolving loans,F,N,Y,1.0,81000.000,270000.0,13500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
19,100023,0.0,Cash loans,F,N,Y,1.0,90000.000,544491.0,17563.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,100025,0.0,Cash loans,F,Y,Y,1.0,202500.000,1132573.5,37561.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,100026,0.0,Cash loans,F,N,N,1.0,450000.000,497520.0,32521.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,100027,0.0,Cash loans,F,N,Y,0.0,83250.000,239850.0,23850.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,100029,0.0,Cash loans,M,Y,N,2.0,135000.000,247500.0,12703.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,100031,1.0,Cash loans,F,N,Y,0.0,112500.000,979992.0,27076.5,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
27,100032,0.0,Cash loans,M,N,Y,1.0,112500.000,327024.0,23827.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,100033,0.0,Cash loans,M,Y,Y,0.0,270000.000,790830.0,57676.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
29,100034,0.0,Revolving loans,M,N,Y,0.0,90000.000,180000.0,9000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
30,100035,0.0,Cash loans,F,N,Y,0.0,292500.000,665892.0,24592.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
31,100036,0.0,Cash loans,F,N,Y,0.0,112500.000,512064.0,25033.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,100037,0.0,Cash loans,F,N,N,0.0,90000.000,199008.0,20893.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,100039,0.0,Cash loans,M,Y,N,1.0,360000.000,733315.5,39069.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,100043,0.0,Cash loans,F,N,Y,2.0,198000.000,641173.5,23157.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30711,135644,0.0,Cash loans,F,N,Y,0.0,135000.000,971280.0,54364.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30712,135645,0.0,Revolving loans,F,Y,Y,0.0,315000.000,225000.0,11250.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
30713,135646,1.0,Cash loans,F,N,Y,0.0,108000.000,263686.5,14724.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30714,135647,0.0,Cash loans,M,Y,N,0.0,157500.000,1546020.0,45333.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30715,135648,1.0,Cash loans,M,N,Y,0.0,135000.000,364896.0,19795.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30716,135649,0.0,Revolving loans,F,N,Y,0.0,85500.000,135000.0,6750.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30717,135651,0.0,Cash loans,M,N,N,1.0,180000.000,1288350.0,34114.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30718,135652,0.0,Revolving loans,M,Y,Y,2.0,261000.000,270000.0,13500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
30722,135658,0.0,Cash loans,F,Y,Y,0.0,180000.000,508495.5,20295.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30723,135659,0.0,Cash loans,F,N,Y,0.0,119250.000,679500.0,22585.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30724,135660,0.0,Revolving loans,F,N,Y,0.0,135000.000,157500.0,7875.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30727,135663,0.0,Cash loans,F,Y,Y,2.0,87493.500,450000.0,23431.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30728,135664,0.0,Cash loans,M,N,N,2.0,90000.000,862560.0,30559.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30729,135665,0.0,Cash loans,F,N,N,0.0,54000.000,314100.0,17167.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30730,135666,1.0,Cash loans,F,N,Y,1.0,72000.000,95940.0,9616.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30732,135668,0.0,Cash loans,F,N,Y,0.0,90000.000,269550.0,12964.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30733,135669,1.0,Cash loans,F,N,Y,0.0,247500.000,1133748.0,33277.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30734,135670,0.0,Cash loans,M,N,Y,0.0,180000.000,938304.0,50121.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30735,135671,0.0,Cash loans,F,Y,Y,0.0,81000.000,932643.0,27400.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
30736,135674,0.0,Cash loans,F,N,Y,0.0,112500.000,513531.0,21888.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
30739,135677,0.0,Cash loans,F,N,N,0.0,112500.000,112068.0,11898.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30740,135680,0.0,Cash loans,F,N,Y,0.0,112500.000,927000.0,27234.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
30741,135681,0.0,Cash loans,F,N,Y,3.0,45000.000,348264.0,20124.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30742,135682,1.0,Cash loans,F,N,N,0.0,67500.000,298512.0,17136.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30744,135685,0.0,Cash loans,F,Y,Y,2.0,202500.000,891072.0,39379.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30745,135686,1.0,Revolving loans,F,N,N,1.0,76500.000,180000.0,9000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30747,135688,0.0,Cash loans,F,Y,N,0.0,112500.000,225000.0,13725.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30748,135689,0.0,Cash loans,M,N,N,0.0,90000.000,298512.0,19206.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
30749,135690,0.0,Cash loans,F,Y,Y,2.0,283500.000,2517300.0,66532.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30750,135691,0.0,Cash loans,M,Y,N,0.0,112500.000,1506816.0,45814.5,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [25]:
df_loan.drop(df_loan.iloc[:, 32:223], inplace = True, axis = 1)

In [26]:
df_loan

,Unnamed: 0,LOAN_ID,LOAN_DEFAULT,CONTRACT_TYPE,GENDER,OWN_CAR,OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,...,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT
1,2,100003,0.0,Cash loans,F,N,N,0.0,270000.000,1293502.5,...,NaN,1.0,1.0,0.0,1.0,1.0,0.0,Core staff,2.0,1.0
2,3,100004,0.0,Revolving loans,M,Y,Y,0.0,67500.000,135000.0,...,26.0,1.0,1.0,1.0,1.0,1.0,0.0,Laborers,1.0,2.0
3,4,100006,0.0,Cash loans,F,N,Y,0.0,135000.000,312682.5,...,NaN,1.0,1.0,0.0,1.0,0.0,0.0,Laborers,2.0,2.0
4,5,100007,0.0,Cash loans,M,N,Y,0.0,121500.000,513000.0,...,NaN,1.0,1.0,0.0,1.0,0.0,0.0,Core staff,1.0,2.0
6,7,100009,0.0,Cash loans,F,Y,Y,1.0,171000.000,1560726.0,...,17.0,1.0,1.0,0.0,1.0,1.0,0.0,Accountants,3.0,2.0
7,8,100010,0.0,Cash loans,M,Y,Y,0.0,360000.000,1530000.0,...,8.0,1.0,1.0,1.0,1.0,0.0,0.0,Managers,2.0,3.0
8,9,100011,0.0,Cash loans,F,N,Y,0.0,112500.000,1019610.0,...,NaN,1.0,0.0,0.0,1.0,0.0,0.0,NaN,2.0,2.0
9,10,100012,0.0,Revolving loans,M,N,Y,0.0,135000.000,405000.0,...,NaN,1.0,1.0,0.0,1.0,0.0,0.0,Laborers,1.0,2.0
10,11,100014,0.0,Cash loans,F,N,Y,1.0,112500.000,652500.0,...,NaN,1.0,1.0,0.0,1.0,0.0,0.0,Core staff,3.0,2.0
11,12,100015,0.0,Cash loans,F,N,Y,0.0,38419.155,148365.0,...,NaN,1.0,0.0,0.0,1.0,1.0,0.0,NaN,2.0,2.0
12,13,100016,0.0,Cash loans,F,N,Y,0.0,67500.000,80865.0,...,NaN,1.0,1.0,1.0,1.0,1.0,0.0,Laborers,2.0,2.0
13,14,100017,0.0,Cash loans,M,Y,N,1.0,225000.000,918468.0,...,23.0,1.0,1.0,0.0,1.0,0.0,0.0,Drivers,3.0,2.0
14,15,100018,0.0,Cash loans,F,N,Y,0.0,189000.000,773680.5,...,NaN,1.0,1.0,0.0,1.0,0.0,0.0,Laborers,2.0,2.0
15,16,100019,0.0,Cash loans,M,Y,Y,0.0,157500.000,299772.0,...,17.0,1.0,1.0,0.0,1.0,0.0,0.0,Laborers,1.0,3.0
16,17,100020,0.0,Cash loans,M,N,N,0.0,108000.000,509602.5,...,NaN,1.0,1.0,0.0,1.0,0.0,0.0,Drivers,2.0,2.0
17,18,100021,0.0,Revolving loans,F,N,Y,1.0,81000.000,270000.0,...,NaN,1.0,1.0,0.0,1.0,0.0,0.0,Laborers,3.0,2.0
19,20,100023,0.0,Cash loans,F,N,Y,1.0,90000.000,544491.0,...,NaN,1.0,1.0,1.0,1.0,1.0,0.0,Core staff,2.0,2.0
21,22,100025,0.0,Cash loans,F,Y,Y,1.0,202500.000,1132573.5,...,14.0,1.0,1.0,0.0,1.0,0.0,0.0,Sales staff,3.0,2.0
22,23,100026,0.0,Cash loans,F,N,N,1.0,450000.000,497520.0,...,NaN,1.0,1.0,0.0,1.0,0.0,0.0,Sales staff,3.0,3.0
23,24,100027,0.0,Cash loans,F,N,Y,0.0,83250.000,239850.0,...,NaN,1.0,0.0,0.0,1.0,1.0,0.0,NaN,2.0,3.0
24,25,100029,0.0,Cash loans,M,Y,N,2.0,135000.000,247500.0,...,7.0,1.0,1.0,0.0,1.0,0.0,0.0,Drivers,4.0,2.0
26,27,100031,1.0,Cash loans,F,N,Y,0.0,112500.000,979992.0,...,NaN,1.0,1.0,0.0,1.0,0.0,0.0,Cooking staff,1.0,3.0
27,28,100032,0.0,Cash loans,M,N,Y,1.0,112500.000,327024.0,...,NaN,1.0,1.0,0.0,1.0,0.0,0.0,Laborers,3.0,2.0
28,29,100033,0.0,Cash loans,M,Y,Y,0.0,270000.000,790830.0,...,1.0,1.0,1.0,0.0,1.0,0.0,1.0,NaN,1.0,1.0
29,30,100034,0.0,Revolving loans,M,N,Y,0.0,90000.000,180000.0,...,NaN,1.0,1.0,0.0,1.0,0.0,0.0,Laborers,1.0,2.0
30,31,100035,0.0,Cash loans,F,N,Y,0.0,292500.000,665892.0,...,NaN,1.0,1.0,0.0,1.0,0.0,1.0,NaN,2.0,2.0
31,32,100036,0.0,Cash loans,F,N,Y,0.0,112500.000,512064.0,...,NaN,1.0,1.0,0.0,1.0,0.0,0.0,Private service staff,2.0,2.0
32,33,100037,0.0,Cash loans,F,N,N,0.0,90000.000,199008.0,...,NaN,1.0,1.0,1.0,1.0,0.0,0.0,Laborers,2.0,2.0
33,34,100039,0.0,Cash loans,M,Y,N,1.0,360000.000,733315.5,...,3.0,1.0,1.0,0.0,1.0,0.0,0.0,Drivers,3.0,2.0
36,37,100043,0.0,Cash loans,F,N,Y,2.0,198000.000,641173.5,...,NaN,1.0,1.0,1.0,1.0,1.0,0.0,Private service staff,4.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30711,30712,135644,0.0,Cash loans,F,N,Y,0.0,135000.000,971280.0,...,NaN,1.0,0.0,0.0,1.0,1.0,0.0,NaN,2.0,2.0
30712,30713,135645,0.0,Revolving loans,F,Y,Y,0.0,315000.000,225000.0,...,13.0,1.0,1.0,0.0,1.0,0.0,0.0,High skill tech staff,2.0,2.0
30713,30714,135646,1.0,Cash loans,F,N,Y,0.0,108000.000,263686.5,...,NaN,1.0,0.0,0.0,1.0,0.0,0.0,NaN,1.0,2.0
30714,30715,135647,0.0,Cash loans,M,Y,N,0.0,157500.000,1546020.0,...,11.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN,2.0,2.0
30715,30716,135648,1.0,Cash loans,M,N,Y,0.0,135000.000,364896.0,...,NaN,1.0,1.0,1.0,1.0,0.0,0.0,Laborers,1.0,3.0
30716,30717,135649,0.0,Revolving loans,F,N,Y,0.0,85500.000,135000.0,...,NaN,1.0,1.0,0.0,1.0,0.0,0.0,Cleaning staff,2.0,2.0
30717,30718,135651,0.0,Cash loans,M,N,N,1.0,180000.000,1288350.0,...,NaN,1.0,1.0,1.0,1.0,1.0,0.0,Laborers,3.0,2.0
30718,30719,135652,0.0,Revolving loans,M,Y,Y,2.0,261000.000,270000.0,...,65.0,1.0,1.0,0.0,1.0,0.0,0.0,Laborers,4.0,2.0
30722,30723,135658,0.0,Cash loans,F,Y,Y,0.0,180000.000,508495.5,...,2.0,1.0,1.0,0.0,1.0,0.0,1.0,Accountants,2.0,2.0
30723,30724,135659,0.0,Cash loans,F,N,Y,0.0,119250.000,679500.0,...,NaN,1.0,1.0,1.0,1.0,0.0,0.0,Accountants,2.0,2.0
30724,30725,135660,0.0,Revolving loans,F,N,Y,0.0,135000.000,157500.0,...,NaN,1.0,1.0,0.0,1.0,1.0,0.0,High skill tech staff,1.0,1.0
30727,30728,135663,0.0,Cash loans,F,Y,Y,2.0,87493.500,450000.0,...,14.0,1.0,1.0,1.0,1.0,0.0,0.0,Core staff,4.0,2.0
30728,30729,135664,0.0,Cash loans,M,N,N,2.0,90000.000,862560.0,...,NaN,1.0,1.0,1.0,1.0,1.0,0.0,Drivers,4.0,2.0
30729,30730,135665,0.0,Cash loans,F,N,N,0.0,54000.000,314100.0,...,NaN,1.0,1.0,0.0,1.0,0.0,0.0,Drivers,1.0,3.0
30730,30731,135666,1.0,Cash loans,F,N,Y,1.0,72000.000,95940.0,...,NaN,1.0,1.0,1.0,1.0,0.0,0.0,NaN,3.0,2.0
30732,30733,135668,0.0,Cash loans,F,N,Y,0.0,90000.000,269550.0,...,NaN,1.0,1.0,0.0,1.0,1.0,0.0,Sales staff,2.0,3.0
30733,30734,135669,1.0,Cash loans,F,N,Y,0.0,247500.000,1133748.0,...,NaN,1.0,1.0,0.0,1.0,0.0,0.0,Sales staff,2.0,2.0
30734,30735,135670,0.0,Cash loans,M,N,Y,0.0,180000.000,938304.0,...,NaN,1.0,1.0,0.0,1.0,1.0,1.0,Drivers,2.0,2.0
30735,30736,135671,0.0,Cash loans,F,Y,Y,0.0,81000.000,932643.0,...,4.0,1.0,1.0,0.0,1.0,0.0,0.0,Managers,2.0,2.0
30736,30737,135674,0.0,Cash loans,F,N,Y,0.0,112500.000,513531.0,...,NaN,1.0,1.0,0.0,1.0,0.0,0.0,NaN,2.0,2.0
30739,30740,135677,0.0,Cash loans,F,N,N,0.0,112500.000,112068.0,...,NaN,1.0,1.0,0.0,1.0,0.0,0.0,Core staff,2.0,2.0
30740,30741,135680,0.0,Cash loans,F,N,Y,0.0,112500.000,927000.0,...,NaN,1.0,1.0,0.0,1.0,0.0,0.0,Sales staff,2.0,2.0
30741,30742,135681,0.0,Cash loans,F,N,Y,3.0,45000.000,348264.0,...,NaN,1.0,1.0,1.0,1.0,0.0,1.0,Laborers,5.0,2.0
30742,30743,135682,1.0,Cash loans,F,N,N,0.0,67500.000,298512.0,...,NaN,1.0,0.0,0.0,1.0,0.0,0.0,NaN,2.0,2.0
30744,30745,135685,0.0,Cash loans,F,Y,Y,2.0,202500.000,891072.0,...,65.0,1.0,0.0,0.0,1.0,0.0,1.0,NaN,4.0,2.0
30745,30746,135686,1.0,Revolving loans,F,N,N,1.0,76500.000,180000.0,...,NaN,1.0,0.0,0.0,1.0,0.0,0.0,NaN,2.0,2.0
30747,30748,135688,0.0,Cash loans,F,Y,N,0.0,112500.000,225000.0,...,14.0,1.0,1.0,1.0,1.0,0.0,0.0,Private service staff,2.0,3.0
30748,30749,135689,0.0,Cash loans,M,N,N,0.0,90000.000,298512.0,...,NaN,1.0,1.0,1.0,1.0,0.0,0.0,NaN,2.0,3.0
30749,30750,135690,0.0,Cash loans,F,Y,Y,2.0,283500.000,2517300.0,...,4.0,1.0,1.0,0.0,1.0,0.0,0.0,Core staff,4.0,3.0
30750,30751,135691,0.0,Cash loans,M,Y,N,0.0,112500.000,1506816.0,...,16.0,1.0,1.0,1.0,1.0,1.0,0.0,Drivers,2.0,2.0

In [ ]:
df_.to_csv(r'cleaned_loan.csv')